# Generated by Django 4.2.7 on 2023-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
