# Generated by Django 4.2.7 on 2023-11-06 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_free'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name="To'lov qilgan"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Iltimos telefon raqamini to'g'ri kiriting.", regex='^998([378]{2}|(9[013-57-9]))\\d{7}$')], verbose_name='Telefon raqam (998991234567)'),
        ),
    ]
