# Generated by Django 4.2.7 on 2023-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_end_date_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
